# https://docs.microsoft.com/azure/devops/pipelines/ecosystems/xcode
pool:
  vmImage: 'macOS-10.14'
variables:
  scheme: ''
  sdk: 'iphoneos'
  configuration: 'Release'

steps:
# - task: InstallAppleCertificate@2
#   inputs:
#     certSecureFile: 'appCertificate.p12'
#     certPwd: $(appCertificatePassword)
#     keychain: 'temp'
#     deleteCert: true
# - task: Xcode@5
#   inputs:
#     actions: 'build'
#     scheme: '$(scheme)'
#     sdk: '$(sdk)'
#     configuration: '$(configuration)'
#     xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
#     xcodeVersion: 'default'
#     signingOption: 'manual'
#     signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
#     provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
#     packageApp: true
# - task: Xcode@5
#   inputs:
#     sdk: '$(sdk)'
#     scheme: '$(scheme)'
#     configuration: '$(configuration)'
#     xcodeVersion: 'default' # Options: default, 10, 9, 8, specifyPath
#     # exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
#     packageApp: false
# - task: Xcode@5
#   inputs:
#     actions: 'build'
#     xcodeVersion: '10'
#     packageApp: true
#     exportOptions: 'specify'
#     exportMethod: 'app-store'
#     exportTeamId: 'agrim'
#     # exportPath: 
#     signingOption: 'nosign'
#     destinationPlatformOption: 'iOS'
#     publishJUnitResults: true

- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: ''
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath
    packageApp: true
    signingOption: 'nosign' # Options: nosign, default, manual, auto
    exportOptions: 'specify'
    exportMethod: 'app-store'
    exportTeamId: 'agrim'
    useXcpretty: false # Makes it easier to diagnose build failures
- task: CopyFiles@2
  inputs:
    contents: '**/*.ipa'
    targetFolder: '$(build.artifactStagingDirectory)'
    overWrite: true
    flattenFolders: true
- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github'
    repositoryName: 'agrim4s/pipelines-xcode'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: userSpecifiedTag
    tag: '$(Build.BuildNumber)'
    title: '$(Build.BuildNumber)'
    assets: '**/*.*p*'
    changeLogCompareToRelease: lastNonDraftRelease
    changeLogType: 'commitBased'