# https://docs.microsoft.com/azure/devops/pipelines/ecosystems/xcode
pool:
  vmImage: 'macOS-10.14'
variables:
  scheme: ''
  sdk: 'iphoneos'
  configuration: 'Release'

steps:
- task: Xcode@5
  inputs:
    sdk: '$(sdk)'
    scheme: '$(scheme)'
    configuration: '$(configuration)'
    xcodeVersion: 'default' # Options: default, 10, 9, 8, specifyPath
    exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
    packageApp: true

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github'
    repositoryName: 'agrim4s/pipelines-android'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: userSpecifiedTag  
    tag: '$(Build.BuildNumber)'  
    title: '$(Build.BuildNumber)'  
    assets: '**/*.*p*'  
    changeLogCompareToRelease: lastNonDraftRelease  
    changeLogType: 'commitBased'