# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute the app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pool:
  vmImage: 'macOS-10.14'

variables:
  scheme: ''
  sdk: 'iphoneos'
  configuration: 'Release'

steps:
- task: Xcode@5
  inputs:
    scheme: ''
    sdk: 'iphoneos'
    configuration: 'Release'
    xcodeVersion: 'default'

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github'
    repositoryName: 'agrim4s/pipelines-xcode'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: userSpecifiedTag  
    tag: '$(Build.BuildNumber)'  
    title: '$(Build.BuildNumber)'  
    assets: '**/*.*p*'  
    changeLogCompareToRelease: lastNonDraftRelease  
    changeLogType: 'commitBased'