# https://docs.microsoft.com/azure/devops/pipelines/ecosystems/xcode
pool:
  vmImage: 'macOS-10.14'
variables:
  scheme: ''
  sdk: 'iphoneos'
  configuration: 'Release'

steps:
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'appCertificate.p12'
    certPwd: $(appCertificatePassword)
    keychain: 'temp'
    deleteCert: true
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: '$(scheme)'
    sdk: '$(sdk)'
    configuration: '$(configuration)'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default'
    signingOption: 'manual'
    signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
    provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
    packageApp: true
# - task: Xcode@5
#   inputs:
#     sdk: '$(sdk)'
#     scheme: '$(scheme)'
#     configuration: '$(configuration)'
#     xcodeVersion: 'default' # Options: default, 10, 9, 8, specifyPath
#     exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
#     packageApp: true

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github'
    repositoryName: 'agrim4s/pipelines-xcode'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: userSpecifiedTag
    tag: '$(Build.BuildNumber)'
    title: '$(Build.BuildNumber)'
    assets: '**/*.*p*'
    changeLogCompareToRelease: lastNonDraftRelease
    changeLogType: 'commitBased'